server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graduation_project?serverTimezone=UTC&characterEncoding=utf-8&useUnicode=true&useSSL=false
    username: root
    password: "ltp123456"
    driver-class-name: com.mysql.cj.jdbc.Driver


